/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bean;

import java.awt.Color;
import java.io.Serializable;

/**
 *
 * @author pawel
 */
public class KonwertFarenheit extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form KonwertFarenheit
     */
    
    private double tempF = 0.0;
    private boolean FC = false;
    private boolean FK = false;
    private boolean FR = false;
    
    
    public KonwertFarenheit() {
        initComponents();
    }
    
    public double getF(){
        return tempF = (double)Integer.parseInt(jTextField1.getText());
    }
    
    public void setF(double f){
        tempF = f;
    }
    
    public double getValue(){
        return getF();
        
    }
    
    public void calcCel(){
        double val = getValue();
        double wynik = (val-32.0)/1.8000;
        java.text.DecimalFormat df = new java.text.DecimalFormat("0.00");
        if(wynik < 10){
            jLabel2.setForeground(Color.blue);
     jLabel2.setText("Wynik: "+df.format(wynik)+" zimno!!!!");
        }else{
         jLabel2.setForeground(Color.black);
     jLabel2.setText("Wynik: "+df.format(wynik));
        }
    }
    
    public void calcKel(double temp){
        getValue();
        double wynik = ((temp-32.0)/1.8000)+273.15;
        java.text.DecimalFormat df = new java.text.DecimalFormat("0.00");
        if(wynik < 283.15){
            jLabel2.setForeground(Color.blue);
     jLabel2.setText("Wynik: "+df.format(wynik)+" zimno!!!!");
        }else {
            jLabel2.setForeground(Color.black);
     jLabel2.setText("Wynik: "+df.format(wynik));
        }
    }
    
     public void calcRan(double temp){
         getValue();
        double wynik = (temp-32.0)+491.67;
        java.text.DecimalFormat df = new java.text.DecimalFormat("0.00");
     if(wynik < 509.67){
            jLabel2.setForeground(Color.blue);
     jLabel2.setText("Wynik: "+df.format(wynik)+" zimno!!!!");
        }else {
            jLabel2.setForeground(Color.black);
     jLabel2.setText("Wynik: "+df.format(wynik));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        FtoC = new javax.swing.JRadioButton();
        FtoK = new javax.swing.JRadioButton();
        FtoR = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Podaj temperature i zaznacz skalę");

        FtoC.setText("F to C");
        FtoC.setActionCommand("F to C");
        FtoC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FtoCItemStateChanged(evt);
            }
        });

        FtoK.setText("F to K");
        FtoK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FtoKItemStateChanged(evt);
            }
        });

        FtoR.setText("F to R");
        FtoR.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FtoRItemStateChanged(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("...");

        jButton1.setText("Konwertuj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FtoC)
                                .addGap(27, 27, 27)
                                .addComponent(FtoK)
                                .addGap(37, 37, 37)
                                .addComponent(FtoR))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FtoK)
                            .addComponent(FtoR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(FtoC)
                        .addGap(19, 19, 19)))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(FC)
            calcCel();
        if(FK)
            calcKel(tempF);
        if(FR)
            calcRan(tempF);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FtoCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FtoCItemStateChanged
        // TODO add your handling code here:
        int source = evt.getStateChange();
        if(source == 1){
            FC = true;
            FtoK.setEnabled(false);
            FtoR.setEnabled(false);
        }else{
            FC = false;
            FtoK.setEnabled(true);
            FtoR.setEnabled(true);
            
        }
    }//GEN-LAST:event_FtoCItemStateChanged

    private void FtoKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FtoKItemStateChanged
        // TODO add your handling code here:
        int source = evt.getStateChange();
        if(source == 1){
            FK = true;
            FtoC.setEnabled(false);
            FtoR.setEnabled(false);
        }else{
            FK = false;
            FtoC.setEnabled(true);
            FtoR.setEnabled(true);
            
        }
    }//GEN-LAST:event_FtoKItemStateChanged

    private void FtoRItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FtoRItemStateChanged
        // TODO add your handling code here:
        int source = evt.getStateChange();
        if(source == 1){
            FR = true;
            FtoC.setEnabled(false);
            FtoK.setEnabled(false);
        }else{
            FR = false;
            FtoC.setEnabled(true);
            FtoK.setEnabled(true);
            
        }
    }//GEN-LAST:event_FtoRItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FtoC;
    private javax.swing.JRadioButton FtoK;
    private javax.swing.JRadioButton FtoR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
